// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * D​e​u​t​s​c​h
	 */
	language_de: string
}

export type TranslationFunctions = {
	/**
	 * Deutsch
	 */
	language_de: () => LocalizedString
}

export type Formatters = {}
